USE mysql;

FLUSH PRIVILEGES;
CHANGE MASTER TO 
MASTER_HOST='master',
MASTER_USER='repl',
MASTER_PASSWORD='1234',
MASTER_PORT=3306,
MASTER_LOG_FILE='mariadb-bin.000004',
MASTER_LOG_POS=4,
MASTER_CONNECT_RETRY=10;
start slave;
